application/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

#Admin Routes
Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {

    Route::get('/', ['as' => 'admin.index', 'middleware' => 'guest', 'uses' => 'IndexController@index']);
    Route::post('login', ['as' => 'admin.login', 'uses' => 'AuthController@login']);
    Route::post('logout', ['as' => 'admin.logout', 'uses' => 'AuthController@logout']);

    Route::group(['middleware' => ['auth', 'role:admin']], function () {
        Route::get('products/filter', ['as' => 'admin.products.filter', 'uses' => 'ProductsController@filter']);
        Route::post('products/uploadZip', ['as' => 'admin.products.uploadZip', 'uses' => 'ProductsController@extractZIP']);
        Route::get('products/trash', ['as' => 'products.trash', 'uses' => 'ProductsController@trash']);
        Route::get('users/trash', ['as' => 'users.trash', 'uses' => 'UsersController@trash']);
        Route::get('categories/trash', ['as' => 'categories.trash', 'uses' => 'CategoriesController@trash']);
        Route::get('dialog/list', ['as' => 'dialog.list', 'uses' => 'DialogController@index']);
        Route::get('dialog/closed', ['as' => 'dialog.closed', 'uses' => 'DialogController@closed']);
        Route::get('dialog/show/{id}', ['as' => 'dialog.show', 'uses' => 'DialogController@show']);
        Route::post('dialog/store/{id}', ['as' => 'dialog.store', 'uses' => 'DialogController@store']);


        Route::get('returns', ['as' => 'rback.index', 'uses' => 'RbackController@index']);
        Route::get('returns/{id}', ['as' => 'rback.show', 'uses' => 'RbackController@show']);

        Route::get('markup', ['as' => 'markup.index', 'uses' => 'MarkupController@index']);
        Route::post('markup', ['as' => 'markup.store', 'uses' => 'MarkupController@store']);

        Route::get('orders', ['as' => 'orders.index', 'uses' => 'OrderController@index']);
        Route::get('orders/detail/{id}', ['as' => 'orders.detail', 'uses' => 'OrderController@showDetail']);
        Route::get('orders/show/{id}', ['as' => 'orders.show', 'uses' => 'OrderController@show']);
        Route::get('orders/delete/{id}', ['as' => 'orders.delete', 'uses' => 'OrderController@destroy']);
        Route::post('order/changeStatus', ['as' => 'orders.changeStatus', 'uses' => 'OrderController@changeStatus']);

        Route::resource('profile', 'ProfileController');
        Route::resource('users', 'UsersController');
        Route::post('users/delete', ['as' => 'admin.users.delete', 'uses' => 'UsersController@destroyAll']);
        Route::post('users/restore', ['as' => 'admin.users.restore', 'uses' => 'UsersController@restoreUser']);
        Route::resource('manufacturer', 'ManufacturerController');
        Route::resource('categories', 'CategoriesController');
        Route::post('categories/delete', ['as' => 'admin.categories.delete', 'uses' => 'CategoriesController@destroyAll']);
        Route::post('categories/restore', ['as' => 'admin.categories.restore', 'uses' => 'CategoriesController@restoreUser']);
        Route::resource('products', 'ProductsController');
        Route::post('products/delete', ['as' => 'admin.products.delete', 'uses' => 'ProductsController@destroyAll']);
        Route::post('products/restore', ['as' => 'admin.products.restore', 'uses' => 'ProductsController@restoreProduct']);

        Route::post('delete/attr', ['as' => 'admin.attribute.delete', 'uses' => 'AttributeController@deleteAttr']);
        Route::resource('pages', 'PageController');
        Route::post('pages/delete', ['as' => 'admin.pages.delete', 'uses' => 'PageController@destroyAll']);
        Route::get('parse', ['as' => 'parse.index', 'uses' => 'ParseController@index']);
        Route::post('parse', ['as' => 'parse.store', 'uses' => 'ParseController@store']);
        Route::post('parseLinks', ['as' => 'parse.links', 'uses' => 'ParseController@links']);
        Route::resource('settings', 'SettingsController');
        Route::resource('banners', 'BannersController');
        Route::resource('news', 'NewsController');
        Route::resource('status', 'StatusController');

        Route::get('price/index', ['as' => 'price.index', 'uses' => 'PriceController@index']);
        Route::post('price/import', ['as' => 'price.import', 'uses' => 'PriceController@import']);
        Route::post('price/parse', ['as' => 'price.parse', 'uses' => 'PriceController@parse']);
        Route::post('price/tires', ['as' => 'price.tires', 'uses' => 'PriceController@uploadTires']);
        Route::post('price/wheels', ['as' => 'price.wheels', 'uses' => 'PriceController@uploadWheels']);
        Route::post('price/motor', ['as' => 'price.motor', 'uses' => 'PriceController@parserMotor']);
    });
});

# Front Routes
Route::group(['namespace' => 'Front'], function () {

    Route::get('/', ['as' => 'index', 'middleware' => 'guest', 'uses' => 'IndexController@index']);
    Route::post('login', ['as' => 'front.login', 'uses' => 'AuthController@login']);
    Route::post('logout', ['as' => 'front.logout', 'uses' => 'AuthController@logout']);
    Route::get('register', ['as' => 'front.register.index', 'uses' => 'AuthController@registerIndex']);
    Route::post('register', ['as' => 'front.register', 'uses' => 'AuthController@register']);

    Route::get('forgot', ['as' => 'front.forgot.index', 'uses' => 'AuthController@forgotIndex']);
    Route::post('forgot', ['as' => 'front.forgot', 'uses' => 'AuthController@forgot']);

    Route::get('/password/reset', 'AuthController@showLinkRequestForm');
    Route::get('/password/reset/{token}', 'AuthController@showResetForm');
    Route::post('/password/reset', 'ResetPasswordController@reset');

    Route::get('categories', ['as' => 'front.categories', 'uses' => 'CategoriesController@index']);
    Route::get('categories/{category}', ['as' => 'front.categories.show', 'uses' => 'CategoriesController@show']);
    Route::get('products/{product}', ['as' => 'front.products.show', 'uses' => 'ProductsController@show']);
    Route::post('cart/add', ['as' => 'front.cart.add', 'uses' => 'CartController@addCart']);

    Route::post('stparts/brand', ['as' => 'stparts.brand', 'uses' => 'SearchController@searchStparts']);
    Route::get('stparts/codebrand/{brand}/{code}', ['as' => 'stparts.codebrand', 'uses' => 'SearchController@codeBrand']);


    Route::post('cart/update', ['as' => 'front.cart.update', 'uses' => 'CartController@updateCart']);
    Route::post('order/make', ['as' => 'front.order.make', 'uses' => 'OrderController@makeOrder']);

    Route::post('cart/content', ['as' => 'front.cart.content', 'uses' => 'CartController@getCart']);
    Route::post('cart/remove', ['as' => 'front.cart.remove', 'uses' => 'CartController@destroyProduct']);
    Route::post('cart/products', ['as' => 'front.cart.products', 'uses' => 'CartController@productsList']);

    Route::resource('news', 'NewsController');
    Route::get('cabinet', ['as' => 'cabinet.index', 'uses' => 'CabinetController@index'])->middleware(['auth']);
    Route::get('page/{id}', ['as' => 'front.page.show', 'uses' => 'PageController@show']);
    Route::get('/{alias}', ['as' => 'front.page.alias', 'uses' => 'PageController@alias']);

//    Route::get('news', ['as' => 'front.news.index', 'uses' => 'NewsController@index']);
//    Route::get('news/{id}', ['as' => 'front.news.show', 'uses' => 'NewsController@show']);
    Route::post('search/any', ['as' => 'front.search.any', 'uses' => 'SearchController@searchByAny']);
    Route::post('search/sku', ['as' => 'front.search.sku', 'uses' => 'SearchController@searchBySku']);
    Route::post('search/avtotek', ['as' => 'front.search.avtotek', 'uses' => 'SearchController@searchAvtotek']);
    Route::get('search/{article}/{brand}', ['as' => 'front.search.articleBrand', 'uses' => 'SearchController@articleBrand']);
    Route::post('trinity/basket/add', ['as' => 'front.trinity.basket.add', 'uses' => 'TrinityController@addBasket']);

    Route::post('index/orderCall', ['as' => 'front.index.orderCall', 'uses' => 'IndexController@orderCall']);
    Route::post('index/feedback', ['as' => 'front.index.feedback', 'uses' => 'IndexController@feedback']);

    Route::post('armtek/search', ['as' => 'armtek.search', 'uses' => 'ArmtekController@search']);
    Route::post('armtek/basket/add', ['as' => 'armtek.basket.add', 'uses' => 'ArmtekController@addBasket']);

    Route::post('favorit/basket/add', ['as' => 'favorit.basket.add', 'uses' => 'FavoritController@addBasket']);
    Route::post('forumauto/basket/add', ['as' => 'forumauto.basket.add', 'uses' => 'ForumAutoController@addBasket']);

//    Route::get('tires/index', ['as' => 'front.tires.index', 'uses' => 'TiresWheelsController@indexTires']);
//    Route::post('tires/tire', ['as' => 'front.tires.tire', 'uses' => 'TiresWheelsController@showTire']);
//    Route::post('tires/basket/add', ['as' => 'front.tires.basket', 'uses' => 'TiresWheelsController@basketTires']);
//    Route::get('tires/filter', ['as' => 'front.tires.filter', 'uses' => 'TiresWheelsController@filterTires']);

//    Route::get('wheels/filter', ['as' => 'front.wheels.filter', 'uses' => 'TiresWheelsController@filterWheels']);
//
//    Route::get('wheels/index', ['as' => 'front.wheels.index', 'uses' => 'TiresWheelsController@indexWheels']);
//    Route::post('wheels/wheel', ['as' => 'front.wheels.wheel', 'uses' => 'TiresWheelsController@showWheel']);
//    Route::post('wheel/basket/add', ['as' => 'front.wheels.basket', 'uses' => 'TiresWheelsController@basketWheel']);


    Route::post('stparts/basket/add', ['as' => 'stparts.basket', 'uses' => 'StpartsController@basket']);

application/resources/views/admin/layouts/_sidebar/sidebar.blade.php
<div class="sidebar responsive">
    <ul class="nav nav-list">
        <li class="{{ ($active == 'products' || $active == 'create_products' || $active == 'products_list' || $active == 'products_trash') ? 'open' : ''}}">
            <a
                    href="#"
                    class="dropdown-toggle">
                <i class="menu-icon fa fa-cubes"></i>
                <span class="menu-text"> {{ trans('interface.panel.products.title') }} </span>
                <b class="arrow fa fa-angle-down"></b>
            </a>

            <i class="arrow"></i>

            <ul class="submenu nav-show">
                <li class="{{ $active == 'products_list' ? 'active' : ''}}">
                    <a href="{{route('products.index')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        <span class="menu-text"> {{ trans('interface.panel.products_list.title') }} </span>
                    </a>
                    <i class="arrow"></i>
                </li>
                <li class="{{ $active == 'create_products' ? 'active' : ''}}">
                    <a href="{{route('products.create')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        {{ trans('interface.panel.create_products.title') }}
                    </a>
                    <b class="arrow"></b>
                </li>
                <li class="{{ $active == 'products_trash' ? 'active' : ''}}">
                    <a href="{{route('products.trash')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        {{ trans('interface.panel.products_trash.title') }}
                    </a>
                    <b class="arrow"></b>
                </li>
            </ul>
        </li>

        <li class="{{ ($active == 'categories' || $active == 'create_categories' || $active == 'categories_list' || $active == 'categories_trash') ? 'open' : ''}}">
            <a
                    href="#"
                    class="dropdown-toggle">
                <i class="menu-icon fa fa-tasks"></i>
                <span class="menu-text"> {{ trans('interface.panel.categories.title') }} </span>
                <b class="arrow fa fa-angle-down"></b>
            </a>

            <i class="arrow"></i>

            <ul class="submenu nav-show">
                <li class="{{ $active == 'categories_list' ? 'active' : ''}}">
                    <a href="{{route('categories.index')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        <span class="menu-text"> {{ trans('interface.panel.categories_list.title') }} </span>
                    </a>
                    <i class="arrow"></i>
                </li>
                <li class="{{ $active == 'create_categories' ? 'active' : ''}}">
                    <a href="{{route('categories.create')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        {{ trans('interface.panel.create_categories.title') }}
                    </a>
                    <b class="arrow"></b>
                </li>
                <li class="{{ $active == 'categories_trash' ? 'active' : ''}}">
                    <a href="{{route('categories.trash')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        {{ trans('interface.panel.categories_trash.title') }}
                    </a>
                    <b class="arrow"></b>
                </li>
            </ul>
        </li>

        <li class="{{ ($active == 'manufacturer' || $active == 'create_manufacturer' || $active == 'manufacturer_list') ? 'open' : ''}}">
            <a
                    href="#"
                    class="dropdown-toggle">
                <i class="menu-icon fa fa-tags"></i>
                <span class="menu-text"> {{ trans('interface.panel.manufacturer.title') }} </span>
                <b class="arrow fa fa-angle-down"></b>
            </a>

            <i class="arrow"></i>

            <ul class="submenu nav-show">
                <li class="{{ $active == 'manufacturer_list' ? 'active' : ''}}">
                    <a href="{{route('manufacturer.index')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        <span class="menu-text"> {{ trans('interface.panel.manufacturer_list.title') }} </span>
                    </a>
                    <i class="arrow"></i>
                </li>
                <li class="{{ $active == 'create_manufacturer' ? 'active' : ''}}">
                    <a href="{{route('manufacturer.create')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        {{ trans('interface.panel.create_manufacturer.title') }}
                    </a>
                    <b class="arrow"></b>
                </li>
            </ul>
        </li>

        <li class="{{ ($active == 'news' || $active == 'edit_news' || $active == 'create_news' || $active == 'news_list') ? 'open' : ''}}">
            <a
                    href="#"
                    class="dropdown-toggle">
                <i class="menu-icon fa fa-newspaper-o"></i>
                <span class="menu-text"> {{ trans('interface.panel.news.title') }} </span>
                <b class="arrow fa fa-angle-down"></b>
            </a>

            <i class="arrow"></i>

            <ul class="submenu nav-show">
                <li class="{{ $active == 'news_list' ? 'active' : ''}}">
                    <a href="{{route('news.index')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        <span class="menu-text"> {{ trans('interface.panel.news_list.title') }} </span>
                    </a>
                    <i class="arrow"></i>
                </li>
                <li class="{{ $active == 'create_news' ? 'active' : ''}}">
                    <a href="{{route('news.create')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        {{ trans('interface.panel.create_news.title') }}
                    </a>
                    <b class="arrow"></b>
                </li>
            </ul>
        </li>

        <li class="{{ ($active == 'users' || $active == 'create_users' || $active == 'users_list' || $active == 'users_trash') ? 'open' : ''}}">
            <a
                    href="#"
                    class="dropdown-toggle">
                <i class="menu-icon fa fa-users"></i>
                <span class="menu-text"> {{ trans('interface.panel.users.title') }} </span>
                <b class="arrow fa fa-angle-down"></b>
            </a>
            <i class="arrow"></i>
            <ul class="submenu nav-show">
                <li class="{{ $active == 'users_list' ? 'active' : ''}}">
                    <a href="{{route('users.index')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        <span class="menu-text"> {{ trans('interface.panel.users_list.title') }} </span>
                    </a>
                    <i class="arrow"></i>
                </li>
                <li class="{{ $active == 'create_users' ? 'active' : ''}}">
                    <a href="{{route('users.create')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        {{ trans('interface.panel.create_users.title') }}
                    </a>
                    <b class="arrow"></b>
                </li>
                <li class="{{ $active == 'users_trash' ? 'active' : ''}}">
                    <a href="{{route('users.trash')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        {{ trans('interface.panel.users_trash.title') }}
                    </a>
                    <b class="arrow"></b>
                </li>
            </ul>
        </li>

        <li class="{{ ($active == 'pages' || $active == 'pages_list' || $active == 'pages_create' || $active == 'pages_edit') ? 'open' : ''}}">
            <a
                    href="#"
                    class="dropdown-toggle">
                <i class="menu-icon fa fa-files-o"></i>
                <span class="menu-text"> {{ trans('interface.panel.pages.title') }} </span>
                <b class="arrow fa fa-angle-down"></b>
            </a>
            <i class="arrow"></i>
            <ul class="submenu nav-show">
                <li class="{{ $active == 'pages_list' ? 'active' : ''}}">
                    <a href="{{route('pages.index')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        <span class="menu-text"> {{ trans('interface.panel.pages_list.title') }} </span>
                    </a>
                    <i class="arrow"></i>
                </li>
                <li class="{{ $active == 'pages_create' ? 'active' : ''}}">
                    <a href="{{route('pages.create')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        <span class="menu-text"> {{ trans('interface.panel.pages_create.title') }} </span>
                    </a>
                    <i class="arrow"></i>
                </li>

            </ul>
        </li>

        <li
                class="{{
($active === 'settings'
|| $active === 'main_page'
|| $active === 'banners'
|| $active === 'create_banner'
|| $active === 'edit_banner'
|| $active === 'price'
|| $active === 'markup'
|| $active ===  'status'
|| $active ===  'parse'
) ? 'open' : ''}}">
            <a
                    href="#"
                    class="dropdown-toggle">
                <i class="menu-icon fa fa-cogs"></i>
                <span class="menu-text"> {{ trans('interface.panel.settings.title') }} </span>
                <b class="arrow fa fa-angle-down"></b>
            </a>
            <i class="arrow"></i>
            <ul class="submenu nav-show">
                <li class="{{ $active === 'main_page' ? 'active' : ''}}">
                    <a href="{{route('settings.index')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        <span class="menu-text"> {{ trans('interface.panel.main_page.title') }} </span>
                    </a>
                    <i class="arrow"></i>
                </li>
                <li class="{{ $active === 'banners' ? 'active' : ''}}">
                    <a href="{{route('banners.index')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        <span class="menu-text"> {{ trans('interface.panel.banner.title') }} </span>
                    </a>
                    <i class="arrow"></i>
                </li>
                <li class="{{ $active === 'price' ? 'active' : ''}}">
                    <a href="{{route('price.index')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        <span class="menu-text"> {{ trans('interface.panel.price.index') }} </span>
                    </a>
                    <i class="arrow"></i>
                </li>
                <li class="{{ $active === 'markup' ? 'active' : ''}}">
                    <a href="{{route('markup.index')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        <span class="menu-text"> {{ trans('interface.panel.markup.index') }} </span>
                    </a>
                    <i class="arrow"></i>
                </li>
                <li class="{{ $active === 'status' ? 'active' : ''}}">
                    <a href="{{route('status.index')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        <span class="menu-text"> {{ trans('interface.panel.status.index') }} </span>
                    </a>
                    <i class="arrow"></i>
                </li>
                <li class="{{ $active === 'parse' ? 'active' : ''}}">
                    <a href="{{route('parse.index')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        <span class="menu-text"> {{ trans('interface.panel.parse.index') }} </span>
                    </a>
                    <i class="arrow"></i>
                </li>

            </ul>
        </li>

        <li class="{{ $active == 'orders' ? 'active' : ''}}">

            <a href="{{route('orders.index')}}">
                <i class="menu-icon fa fa-handshake-o"></i>
                <span class="menu-text"> {{ trans('interface.panel.orders.title') }} </span>
            </a>
            <i class="arrow"></i>
        </li>
        <li class="{{ $active == 'rback' ? 'active' : ''}}">

            <a href="{{route('rback.index')}}">
                <i class="menu-icon fa fa-thumbs-o-down"></i>
                <span class="menu-text"> {{ trans('interface.panel.rback.index') }} </span>
            </a>
            <i class="arrow"></i>
        </li>
        <li
                class="{{ $active == 'profile' ? 'active' : ''}}"
                style="display: none;">

            <a href="{{route('profile.index')}}">
                <i class="menu-icon fa fa-vcard-o"></i>
                <span class="menu-text"> {{ trans('interface.panel.profile.title') }} </span>
            </a>
            <i class="arrow"></i>
        </li>
    </ul>
</div>