application/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

#Admin Routes
Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {

    Route::get('/', ['as' => 'admin.index', 'middleware' => 'guest', 'uses' => 'IndexController@index']);
    Route::post('login', ['as' => 'admin.login', 'uses' => 'AuthController@login']);
    Route::post('logout', ['as' => 'admin.logout', 'uses' => 'AuthController@logout']);

    Route::group(['middleware' => ['auth', 'role:admin']], function () {
        Route::get('products/filter', ['as' => 'admin.products.filter', 'uses' => 'ProductsController@filter']);
        Route::post('products/uploadZip', ['as' => 'admin.products.uploadZip', 'uses' => 'ProductsController@extractZIP']);
        Route::get('products/trash', ['as' => 'products.trash', 'uses' => 'ProductsController@trash']);
        Route::get('users/trash', ['as' => 'users.trash', 'uses' => 'UsersController@trash']);
        Route::get('categories/trash', ['as' => 'categories.trash', 'uses' => 'CategoriesController@trash']);
        Route::get('dialog/list', ['as' => 'dialog.list', 'uses' => 'DialogController@index']);
        Route::get('dialog/closed', ['as' => 'dialog.closed', 'uses' => 'DialogController@closed']);
        Route::get('dialog/show/{id}', ['as' => 'dialog.show', 'uses' => 'DialogController@show']);
        Route::post('dialog/store/{id}', ['as' => 'dialog.store', 'uses' => 'DialogController@store']);


        Route::get('returns', ['as' => 'rback.index', 'uses' => 'RbackController@index']);
        Route::get('returns/{id}', ['as' => 'rback.show', 'uses' => 'RbackController@show']);

        Route::get('markup', ['as' => 'markup.index', 'uses' => 'MarkupController@index']);
        Route::post('markup', ['as' => 'markup.store', 'uses' => 'MarkupController@store']);

        Route::get('orders', ['as' => 'orders.index', 'uses' => 'OrderController@index']);
        Route::get('orders/detail/{id}', ['as' => 'orders.detail', 'uses' => 'OrderController@showDetail']);
        Route::get('orders/show/{id}', ['as' => 'orders.show', 'uses' => 'OrderController@show']);
        Route::get('orders/delete/{id}', ['as' => 'orders.delete', 'uses' => 'OrderController@destroy']);
        Route::post('order/changeStatus', ['as' => 'orders.changeStatus', 'uses' => 'OrderController@changeStatus']);

        Route::resource('profile', 'ProfileController');
        Route::resource('users', 'UsersController');
        Route::post('users/delete', ['as' => 'admin.users.delete', 'uses' => 'UsersController@destroyAll']);
        Route::post('users/restore', ['as' => 'admin.users.restore', 'uses' => 'UsersController@restoreUser']);
        Route::resource('manufacturer', 'ManufacturerController');
        Route::resource('categories', 'CategoriesController');
        Route::post('categories/delete', ['as' => 'admin.categories.delete', 'uses' => 'CategoriesController@destroyAll']);
        Route::post('categories/restore', ['as' => 'admin.categories.restore', 'uses' => 'CategoriesController@restoreUser']);
        Route::resource('products', 'ProductsController');
        Route::post('products/delete', ['as' => 'admin.products.delete', 'uses' => 'ProductsController@destroyAll']);
        Route::post('products/restore', ['as' => 'admin.products.restore', 'uses' => 'ProductsController@restoreProduct']);

        Route::post('delete/attr', ['as' => 'admin.attribute.delete', 'uses' => 'AttributeController@deleteAttr']);
        Route::resource('pages', 'PageController');
        Route::post('pages/delete', ['as' => 'admin.pages.delete', 'uses' => 'PageController@destroyAll']);
        Route::get('parse', ['as' => 'parse.index', 'uses' => 'ParseController@index']);
        Route::post('parse', ['as' => 'parse.store', 'uses' => 'ParseController@store']);
        Route::post('parseLinks', ['as' => 'parse.links', 'uses' => 'ParseController@links']);
        Route::resource('settings', 'SettingsController');
        Route::resource('banners', 'BannersController');
        Route::resource('news', 'NewsController');
        Route::resource('status', 'StatusController');

        Route::get('price/index', ['as' => 'price.index', 'uses' => 'PriceController@index']);
        Route::post('price/import', ['as' => 'price.import', 'uses' => 'PriceController@import']);
        Route::post('price/parse', ['as' => 'price.parse', 'uses' => 'PriceController@parse']);
        Route::post('price/tires', ['as' => 'price.tires', 'uses' => 'PriceController@uploadTires']);
        Route::post('price/wheels', ['as' => 'price.wheels', 'uses' => 'PriceController@uploadWheels']);
        Route::post('price/motor', ['as' => 'price.motor', 'uses' => 'PriceController@parserMotor']);
    });
});

# Front Routes
Route::group(['namespace' => 'Front'], function () {

    Route::get('/', ['as' => 'index', 'middleware' => 'guest', 'uses' => 'IndexController@index']);
    Route::post('login', ['as' => 'front.login', 'uses' => 'AuthController@login']);
    Route::post('logout', ['as' => 'front.logout', 'uses' => 'AuthController@logout']);
    Route::get('register', ['as' => 'front.register.index', 'uses' => 'AuthController@registerIndex']);
    Route::post('register', ['as' => 'front.register', 'uses' => 'AuthController@register']);

    Route::get('forgot', ['as' => 'front.forgot.index', 'uses' => 'AuthController@forgotIndex']);
    Route::post('forgot', ['as' => 'front.forgot', 'uses' => 'AuthController@forgot']);

    Route::get('/password/reset', 'AuthController@showLinkRequestForm');
    Route::get('/password/reset/{token}', 'AuthController@showResetForm');
    Route::post('/password/reset', 'ResetPasswordController@reset');

    Route::get('categories', ['as' => 'front.categories', 'uses' => 'CategoriesController@index']);
    Route::get('categories/{category}', ['as' => 'front.categories.show', 'uses' => 'CategoriesController@show']);
    Route::get('products/{product}', ['as' => 'front.products.show', 'uses' => 'ProductsController@show']);
    Route::post('cart/add', ['as' => 'front.cart.add', 'uses' => 'CartController@addCart']);

    Route::post('stparts/brand', ['as' => 'stparts.brand', 'uses' => 'SearchController@searchStparts']);
    Route::get('stparts/codebrand/{brand}/{code}', ['as' => 'stparts.codebrand', 'uses' => 'SearchController@codeBrand']);


    Route::post('cart/update', ['as' => 'front.cart.update', 'uses' => 'CartController@updateCart']);
    Route::post('order/make', ['as' => 'front.order.make', 'uses' => 'OrderController@makeOrder']);

    Route::post('cart/content', ['as' => 'front.cart.content', 'uses' => 'CartController@getCart']);
    Route::post('cart/remove', ['as' => 'front.cart.remove', 'uses' => 'CartController@destroyProduct']);
    Route::post('cart/products', ['as' => 'front.cart.products', 'uses' => 'CartController@productsList']);

    Route::resource('news', 'NewsController');
    Route::get('cabinet', ['as' => 'cabinet.index', 'uses' => 'CabinetController@index'])->middleware(['auth']);
    Route::get('page/{id}', ['as' => 'front.page.show', 'uses' => 'PageController@show']);
    Route::get('/{alias}', ['as' => 'front.page.alias', 'uses' => 'PageController@alias']);

//    Route::get('news', ['as' => 'front.news.index', 'uses' => 'NewsController@index']);
//    Route::get('news/{id}', ['as' => 'front.news.show', 'uses' => 'NewsController@show']);
    Route::post('search/any', ['as' => 'front.search.any', 'uses' => 'SearchController@searchByAny']);
    Route::post('search/sku', ['as' => 'front.search.sku', 'uses' => 'SearchController@searchBySku']);
    Route::post('search/avtotek', ['as' => 'front.search.avtotek', 'uses' => 'SearchController@searchAvtotek']);
    Route::get('search/{article}/{brand}', ['as' => 'front.search.articleBrand', 'uses' => 'SearchController@articleBrand']);
    Route::post('trinity/basket/add', ['as' => 'front.trinity.basket.add', 'uses' => 'TrinityController@addBasket']);

    Route::post('index/orderCall', ['as' => 'front.index.orderCall', 'uses' => 'IndexController@orderCall']);
    Route::post('index/feedback', ['as' => 'front.index.feedback', 'uses' => 'IndexController@feedback']);

    Route::post('armtek/search', ['as' => 'armtek.search', 'uses' => 'ArmtekController@search']);
    Route::post('armtek/basket/add', ['as' => 'armtek.basket.add', 'uses' => 'ArmtekController@addBasket']);

    Route::post('favorit/basket/add', ['as' => 'favorit.basket.add', 'uses' => 'FavoritController@addBasket']);
    Route::post('forumauto/basket/add', ['as' => 'forumauto.basket.add', 'uses' => 'ForumAutoController@addBasket']);

//    Route::get('tires/index', ['as' => 'front.tires.index', 'uses' => 'TiresWheelsController@indexTires']);
//    Route::post('tires/tire', ['as' => 'front.tires.tire', 'uses' => 'TiresWheelsController@showTire']);
//    Route::post('tires/basket/add', ['as' => 'front.tires.basket', 'uses' => 'TiresWheelsController@basketTires']);
//    Route::get('tires/filter', ['as' => 'front.tires.filter', 'uses' => 'TiresWheelsController@filterTires']);

//    Route::get('wheels/filter', ['as' => 'front.wheels.filter', 'uses' => 'TiresWheelsController@filterWheels']);
//
//    Route::get('wheels/index', ['as' => 'front.wheels.index', 'uses' => 'TiresWheelsController@indexWheels']);
//    Route::post('wheels/wheel', ['as' => 'front.wheels.wheel', 'uses' => 'TiresWheelsController@showWheel']);
//    Route::post('wheel/basket/add', ['as' => 'front.wheels.basket', 'uses' => 'TiresWheelsController@basketWheel']);


    Route::post('stparts/basket/add', ['as' => 'stparts.basket', 'uses' => 'StpartsController@basket']);

application/resources/views/admin/pages/pages/create.blade.php
@extends('admin.layouts.app')
@section('title')
    {{ trans('interface.panel.pages_create.title') }}
@stop
@section('styles')
    <link rel="stylesheet" href="{{ asset('ace/components/chosen/chosen.css') }}">
    @parent
@stop
@section('content')
    @include("admin.layouts._main.header")
    <div class="container main-container">
        @include('admin.layouts._sidebar.sidebar', ['active' => 'pages_create'])
        <div class="content">
            <div class="page-content">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="page-header">
                            <div class="row">
                                <div class="col-sm-6 col-xs-12 text-left">
                                    <h1>
                                        {{ trans('interface.panel.pages_create.title') }}
                                    </h1>
                                </div>

                            </div>
                        </div>

                        <form action="{{route('pages.store')}}" method="post">
                            {{csrf_field()}}
                            <input type="hidden" value="page" name="type">
                            <div class="row">
                                <div class="col-sm-6 col-xs-12">
                                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                        <label>Название</label>
                                        <input type="text" name="name" placeholder="О нас" class="form-control" value="{{ old('name') }}" autofocus required>
                                        @if ($errors->has('name'))
                                            <span class="help-block">
                                                <strong>
                                                    <small>{{ $errors->first('name') }}</small>
                                                </strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-sm-6 col-xs-12">
                                    <div class="form-group{{ $errors->has('parent_page') ? ' has-error' : '' }}">
                                        <label>Родительская страница</label>
                                        <select class="form-control chosen-select" name="parent_page" data-placeholder="Выбрать страницу">
                                            <option value="0">Выбрать страницу</option>
                                            @foreach($pages as $page)

                                                <option value="{{$page->id}}" {{(old('parent_page') == $page->id ? 'selected':'')}}>{{$page->name}}</option>
                                            @endforeach
                                        </select>
                                        @if ($errors->has('parent_page'))
                                            <span class="help-block">
                                                <strong>
                                                    <small>{{ $errors->first('parent_page') }}</small>
                                                </strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6 col-xs-12">
                                    <div class="form-group{{ $errors->has('sort') ? ' has-error' : '' }}">
                                        <label>Порядок сортировки</label>
                                        <input type="number" name="sort" placeholder="1" class="form-control" value="{{ old('sort') }}">
                                        @if ($errors->has('sort'))
                                            <span class="help-block">
                                                <strong>
                                                    <small>{{ $errors->first('sort') }}</small>
                                                </strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-sm-6 col-xs-12">
                                    <div class="form-group{{ $errors->has('menu') ? ' has-error' : '' }}">
                                        <label>Меню</label>
                                        <select class="form-control chosen-select" name="menu" data-placeholder="Выбрать Меню">
                                            <option value="0">Выбрать страницу</option>
                                            @foreach($menus as $key => $menu)

                                                <option value="{{$key}}" {{(old('menu') == $key ? 'selected':'')}}>{{$menu}}</option>
                                            @endforeach
                                        </select>
                                        @if ($errors->has('menu'))
                                            <span class="help-block">
                                                <strong>
                                                    <small>{{ $errors->first('menu') }}</small>
                                                </strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6 col-xs-12">
                                    <div class="form-group{{ $errors->has('url') ? ' has-error' : '' }}">
                                        <label>Ссылка <small>Если внешний источник</small></label>
                                        <input type="text" name="url" value="{{old('url')}}" id="url" class="form-control" placeholder="http://ya.ru">
                                        @if ($errors->has('url'))
                                            <span class="help-block">
                                                <strong>
                                                    <small>{{ $errors->first('url') }}</small>
                                                </strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-sm-6 col-xs-12">
                                    <div class="form-group{{ $errors->has('alias') ? ' has-error' : '' }}">
                                        <label>Алиас</label>
                                        <input type="text" name="alias" value="{{old('alias')}}" id="alias" class="form-control" placeholder="o_nas">
                                        @if ($errors->has('alias'))
                                            <span class="help-block">
                                                <strong>
                                                    <small>{{ $errors->first('alias') }}</small>
                                                </strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <h3>Seo данные: </h3>
                            <div class="form-group{{ $errors->has('title_seo') ? ' has-error' : '' }}">
                                <label>Название (title)</label>
                                <input type="text" name="title_seo" placeholder="О нас" class="form-control" value="{{ old('title_seo') }}" required>
                                @if ($errors->has('title_seo'))
                                    <span class="help-block">
                                        <strong>
                                            <small>{{ $errors->first('title_seo') }}</small>
                                        </strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('keywords_seo') ? ' has-error' : '' }}">
                                <label>Ключевые слова (keywords)</label>
                                <div>
                                    <input type="text" name="keywords_seo" id="keywords_seo" class="form-control" value="{{ old('keywords_seo') }}">
                                </div>
                                @if ($errors->has('keywords_seo'))
                                    <span class="help-block">
                                        <strong>
                                            <small>{{ $errors->first('keywords_seo') }}</small>
                                        </strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('description_seo') ? ' has-error' : '' }}">
                                <label>Описание (description)</label>
                                <textarea name="description_seo" class="form-control">{{ old('description_seo') }}</textarea>
                                @if ($errors->has('description_seo'))
                                    <span class="help-block">
                                        <strong>
                                            <small>{{ $errors->first('description_seo') }}</small>
                                        </strong>
                                    </span>
                                @endif
                            </div>
                            <div class="editor-wrapper form-group{{ $errors->has('full_description') ? ' has-error' : '' }}">
                                <label>Описание для страницы</label>
                                <div class="wysiwyg-editor" id="full_description">{{ old('full_description') }}</div>
                                <textarea name="full_description" class="form-control">{{ old('full_description') }}</textarea>
                                @if ($errors->has('full_description'))
                                    <span class="help-block">
                                        <strong>
                                            <small>{{ $errors->first('full_description') }}</small>
                                        </strong>
                                    </span>
                                @endif
                            </div>

                            <div class="form-group text-right">
                                <button type="submit" class="btn btn-success">Добавить</button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
    @include("admin.layouts._main.footer")
@endsection
@section('scripts')
    @parent

    <script src="{{asset('ace/components/_mod/bootstrap-wysiwyg/bootstrap-wysiwyg.min.js')}}"></script>
    <script src="{{asset('ace/components/jquery.hotkeys/index.min.js')}}"></script>
    <script src="{{asset('ace/components/chosen/chosen.jquery.js')}}"></script>
    <script src="{{asset('ace/assets/js/src/elements.wysiwyg.js')}}"></script>
    <script src="{{asset('ace/assets/js/src/elements.colorpicker.js')}}"></script>
    <script src="{{asset('ace/components/_mod/bootstrap-tag/bootstrap-tag.js')}}"></script>
    <script src="{{asset('ace/assets/js/src/elements.typeahead.js')}}"></script>
    <script src="{{asset('js/admin/pages.js')}}"></script>
@endsection

application/resources/views/admin/pages/pages/index.blade.php
@extends('admin.layouts.app')
@section('title')
    {{ trans('interface.panel.pages_list.title') }}
@stop
@section('styles')
    @parent
@stop
@section('content')
    @include("admin.layouts._main.header")
    <div class="container main-container">
        @include('admin.layouts._sidebar.sidebar', ['active' => 'pages_list'])
        <div class="content">
            <div class="page-content">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="page-header">
                            <div class="row">
                                <div class="col-sm-6 col-xs-12 text-left">
                                    <h1>
                                        {{ trans('interface.panel.pages_list.title') }}
                                    </h1>
                                </div>
                            </div>
                        </div>
                        @if (session('success'))
                            <div class="alert alert-success">{{ session()->get('success') }}</div>
                        @endif
                        @if (session('danger'))
                            <div class="alert alert-danger">{{ session()->get('danger') }}</div>
                        @endif

                        <div class="row">
                            <div class="col-xs-12 text-right">
                                <div class="pull-right tableTools-container">
                                    <button class="btn btn-xs btn-danger tooltip-info" data-rel="tooltip" data-placement="top" data-original-title="Удалить выбранные" onclick="deletePages(false)">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                        <table id="pageTable" class="table table-striped table-bordered table-hover">
                            <thead class="thin-border-bottom">
                            <tr>
                                <th class="center sorting_disabled">
                                    <label class="pos-rel">
                                        <input type="checkbox" class="ace">
                                        <span class="lbl"></span>
                                    </label>
                                </th>
                                <th>
                                    id
                                </th>
                                <th>
                                    Название
                                </th>
                                <th>
                                    Меню
                                </th>
                                <th class="text-center">
                                    <i class="ace-icon fa fa-cogs"></i>
                                </th>
                            </tr>
                            </thead>
                            <tbody></tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
    @include("admin.layouts._main.footer")
@endsection
@section('scripts')
    @parent
    <script src="{{asset('ace/components/bootbox.js/bootbox.js')}}"></script>
    <script src="{{asset('ace/components/datatables/media/js/jquery.dataTables.js')}}"></script>
    <script src="{{asset('ace/components/_mod/datatables/jquery.dataTables.bootstrap.js')}}"></script>
    <script src="{{asset('ace/components/datatables.net-select/js/dataTables.select.js')}}"></script>
    <script src="{{asset('js/admin/pages.js')}}"></script>
@endsection