application/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

#Admin Routes
Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {

    Route::get('/', ['as' => 'admin.index', 'middleware' => 'guest', 'uses' => 'IndexController@index']);
    Route::post('login', ['as' => 'admin.login', 'uses' => 'AuthController@login']);
    Route::post('logout', ['as' => 'admin.logout', 'uses' => 'AuthController@logout']);

    Route::group(['middleware' => ['auth', 'role:admin']], function () {
        Route::get('products/filter', ['as' => 'admin.products.filter', 'uses' => 'ProductsController@filter']);
        Route::post('products/uploadZip', ['as' => 'admin.products.uploadZip', 'uses' => 'ProductsController@extractZIP']);
        Route::get('products/trash', ['as' => 'products.trash', 'uses' => 'ProductsController@trash']);
        Route::get('users/trash', ['as' => 'users.trash', 'uses' => 'UsersController@trash']);
        Route::get('categories/trash', ['as' => 'categories.trash', 'uses' => 'CategoriesController@trash']);
        Route::get('dialog/list', ['as' => 'dialog.list', 'uses' => 'DialogController@index']);
        Route::get('dialog/closed', ['as' => 'dialog.closed', 'uses' => 'DialogController@closed']);
        Route::get('dialog/show/{id}', ['as' => 'dialog.show', 'uses' => 'DialogController@show']);
        Route::post('dialog/store/{id}', ['as' => 'dialog.store', 'uses' => 'DialogController@store']);


        Route::get('returns', ['as' => 'rback.index', 'uses' => 'RbackController@index']);
        Route::get('returns/{id}', ['as' => 'rback.show', 'uses' => 'RbackController@show']);

        Route::get('markup', ['as' => 'markup.index', 'uses' => 'MarkupController@index']);
        Route::post('markup', ['as' => 'markup.store', 'uses' => 'MarkupController@store']);

        Route::get('orders', ['as' => 'orders.index', 'uses' => 'OrderController@index']);
        Route::get('orders/detail/{id}', ['as' => 'orders.detail', 'uses' => 'OrderController@showDetail']);
        Route::get('orders/show/{id}', ['as' => 'orders.show', 'uses' => 'OrderController@show']);
        Route::get('orders/delete/{id}', ['as' => 'orders.delete', 'uses' => 'OrderController@destroy']);
        Route::post('order/changeStatus', ['as' => 'orders.changeStatus', 'uses' => 'OrderController@changeStatus']);

        Route::resource('profile', 'ProfileController');
        Route::resource('users', 'UsersController');
        Route::post('users/delete', ['as' => 'admin.users.delete', 'uses' => 'UsersController@destroyAll']);
        Route::post('users/restore', ['as' => 'admin.users.restore', 'uses' => 'UsersController@restoreUser']);
        Route::resource('manufacturer', 'ManufacturerController');
        Route::resource('categories', 'CategoriesController');
        Route::post('categories/delete', ['as' => 'admin.categories.delete', 'uses' => 'CategoriesController@destroyAll']);
        Route::post('categories/restore', ['as' => 'admin.categories.restore', 'uses' => 'CategoriesController@restoreUser']);
        Route::resource('products', 'ProductsController');
        Route::post('products/delete', ['as' => 'admin.products.delete', 'uses' => 'ProductsController@destroyAll']);
        Route::post('products/restore', ['as' => 'admin.products.restore', 'uses' => 'ProductsController@restoreProduct']);

        Route::post('delete/attr', ['as' => 'admin.attribute.delete', 'uses' => 'AttributeController@deleteAttr']);
        Route::resource('pages', 'PageController');
        Route::post('pages/delete', ['as' => 'admin.pages.delete', 'uses' => 'PageController@destroyAll']);
        Route::get('parse', ['as' => 'parse.index', 'uses' => 'ParseController@index']);
        Route::post('parse', ['as' => 'parse.store', 'uses' => 'ParseController@store']);
        Route::post('parseLinks', ['as' => 'parse.links', 'uses' => 'ParseController@links']);
        Route::resource('settings', 'SettingsController');
        Route::resource('banners', 'BannersController');
        Route::resource('news', 'NewsController');
        Route::resource('status', 'StatusController');

        Route::get('price/index', ['as' => 'price.index', 'uses' => 'PriceController@index']);
        Route::post('price/import', ['as' => 'price.import', 'uses' => 'PriceController@import']);
        Route::post('price/parse', ['as' => 'price.parse', 'uses' => 'PriceController@parse']);
        Route::post('price/tires', ['as' => 'price.tires', 'uses' => 'PriceController@uploadTires']);
        Route::post('price/wheels', ['as' => 'price.wheels', 'uses' => 'PriceController@uploadWheels']);
        Route::post('price/motor', ['as' => 'price.motor', 'uses' => 'PriceController@parserMotor']);
    });
});

# Front Routes
Route::group(['namespace' => 'Front'], function () {

    Route::get('/', ['as' => 'index', 'middleware' => 'guest', 'uses' => 'IndexController@index']);
    Route::post('login', ['as' => 'front.login', 'uses' => 'AuthController@login']);
    Route::post('logout', ['as' => 'front.logout', 'uses' => 'AuthController@logout']);
    Route::get('register', ['as' => 'front.register.index', 'uses' => 'AuthController@registerIndex']);
    Route::post('register', ['as' => 'front.register', 'uses' => 'AuthController@register']);

    Route::get('forgot', ['as' => 'front.forgot.index', 'uses' => 'AuthController@forgotIndex']);
    Route::post('forgot', ['as' => 'front.forgot', 'uses' => 'AuthController@forgot']);

    Route::get('/password/reset', 'AuthController@showLinkRequestForm');
    Route::get('/password/reset/{token}', 'AuthController@showResetForm');
    Route::post('/password/reset', 'ResetPasswordController@reset');

    Route::get('categories', ['as' => 'front.categories', 'uses' => 'CategoriesController@index']);
    Route::get('categories/{category}', ['as' => 'front.categories.show', 'uses' => 'CategoriesController@show']);
    Route::get('products/{product}', ['as' => 'front.products.show', 'uses' => 'ProductsController@show']);
    Route::post('cart/add', ['as' => 'front.cart.add', 'uses' => 'CartController@addCart']);

    Route::post('stparts/brand', ['as' => 'stparts.brand', 'uses' => 'SearchController@searchStparts']);
    Route::get('stparts/codebrand/{brand}/{code}', ['as' => 'stparts.codebrand', 'uses' => 'SearchController@codeBrand']);


    Route::post('cart/update', ['as' => 'front.cart.update', 'uses' => 'CartController@updateCart']);
    Route::post('order/make', ['as' => 'front.order.make', 'uses' => 'OrderController@makeOrder']);

    Route::post('cart/content', ['as' => 'front.cart.content', 'uses' => 'CartController@getCart']);
    Route::post('cart/remove', ['as' => 'front.cart.remove', 'uses' => 'CartController@destroyProduct']);
    Route::post('cart/products', ['as' => 'front.cart.products', 'uses' => 'CartController@productsList']);

    Route::resource('news', 'NewsController');
    Route::get('cabinet', ['as' => 'cabinet.index', 'uses' => 'CabinetController@index'])->middleware(['auth']);
    Route::get('page/{id}', ['as' => 'front.page.show', 'uses' => 'PageController@show']);
    Route::get('/{alias}', ['as' => 'front.page.alias', 'uses' => 'PageController@alias']);

//    Route::get('news', ['as' => 'front.news.index', 'uses' => 'NewsController@index']);
//    Route::get('news/{id}', ['as' => 'front.news.show', 'uses' => 'NewsController@show']);
    Route::post('search/any', ['as' => 'front.search.any', 'uses' => 'SearchController@searchByAny']);
    Route::post('search/sku', ['as' => 'front.search.sku', 'uses' => 'SearchController@searchBySku']);
    Route::post('search/avtotek', ['as' => 'front.search.avtotek', 'uses' => 'SearchController@searchAvtotek']);
    Route::get('search/{article}/{brand}', ['as' => 'front.search.articleBrand', 'uses' => 'SearchController@articleBrand']);
    Route::post('trinity/basket/add', ['as' => 'front.trinity.basket.add', 'uses' => 'TrinityController@addBasket']);

    Route::post('index/orderCall', ['as' => 'front.index.orderCall', 'uses' => 'IndexController@orderCall']);
    Route::post('index/feedback', ['as' => 'front.index.feedback', 'uses' => 'IndexController@feedback']);

    Route::post('armtek/search', ['as' => 'armtek.search', 'uses' => 'ArmtekController@search']);
    Route::post('armtek/basket/add', ['as' => 'armtek.basket.add', 'uses' => 'ArmtekController@addBasket']);

    Route::post('favorit/basket/add', ['as' => 'favorit.basket.add', 'uses' => 'FavoritController@addBasket']);
    Route::post('forumauto/basket/add', ['as' => 'forumauto.basket.add', 'uses' => 'ForumAutoController@addBasket']);

//    Route::get('tires/index', ['as' => 'front.tires.index', 'uses' => 'TiresWheelsController@indexTires']);
//    Route::post('tires/tire', ['as' => 'front.tires.tire', 'uses' => 'TiresWheelsController@showTire']);
//    Route::post('tires/basket/add', ['as' => 'front.tires.basket', 'uses' => 'TiresWheelsController@basketTires']);
//    Route::get('tires/filter', ['as' => 'front.tires.filter', 'uses' => 'TiresWheelsController@filterTires']);

//    Route::get('wheels/filter', ['as' => 'front.wheels.filter', 'uses' => 'TiresWheelsController@filterWheels']);
//
//    Route::get('wheels/index', ['as' => 'front.wheels.index', 'uses' => 'TiresWheelsController@indexWheels']);
//    Route::post('wheels/wheel', ['as' => 'front.wheels.wheel', 'uses' => 'TiresWheelsController@showWheel']);
//    Route::post('wheel/basket/add', ['as' => 'front.wheels.basket', 'uses' => 'TiresWheelsController@basketWheel']);


    Route::post('stparts/basket/add', ['as' => 'stparts.basket', 'uses' => 'StpartsController@basket']);

application/app/Models/Product.php
<?php

namespace App\Models;

use App\Traits\SeoTrait;
use App\Traits\UploadThumb;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Sofa\Eloquence\Eloquence;

/**
 * Class Product
 * @package App\Models
 */
class Product extends Model
{
    use UploadThumb, SeoTrait, SoftDeletes, Eloquence;

    const CLARIFY_PRICE = 'Уточните цену по телефону';
    /**
     * @var array
     */
    protected $fillable = [
        'name',
        'model_product',
        'sku',
        'price',
        'quantity',
        'minimum',
        'stock_status_id',
        'date_available',
        'status',
        'sort_order',
        'manufacturer_id',
        'id_1c',
        'special',
    ];

    /**
     * @var array
     */
    protected $searchableColumns = ['name', 'model_product', 'sku', 'price', 'attributes.value', 'attributes.name'];

    /**
     * @return array
     */
    public function getDates()
    {
        return ['created_at', 'date_available', 'updated_at', 'deleted_at'];
    }

    /**
     * @return void
     */
    public static function boot()
    {

        parent::boot();

        static::restoring(static function ($product) {

            $thumb = $product->thumb()->withTrashed()->first();
            if (count($thumb) > 0) {
                $thumb->restore();
            }
        });

        static::deleting(static function ($product) {

            $thumb = $product->thumb()->withTrashed()->first();
            $seo = $product->seo()->first();

            if (count($thumb) > 0) {
                if ($product->forceDeleting) {
                    $thumb->forceDelete();
                } else {
                    $thumb->delete();
                }
            }
            if (count($seo) > 0) {
                if ($product->forceDeleting) {
                    $seo->forceDelete();
                }
            }

            if ($product->forceDeleting) {

                $q = 'DELETE FROM category_product where product_id = ?';
                \DB::delete($q, [$product->id]);
                $q2 = 'DELETE FROM manufacturer_product where product_id = ?';
                \DB::delete($q2, [$product->id]);
            }

        });
    }

    /**
     * @param $value
     * @return int
     */
    public function getPriceAttribute($value)
    {
        return (int)$value;
    }

    /**
     * @param $value
     * @return int
     */
    public function getQuantityAttribute($value)
    {
        return (int)$value;
    }

    /**
     * @return string
     */
    public function getStockStatusAttribute()
    {
        $stock_status = $this->stockStatus()->first();
        if ($stock_status !== null) {
            $status = $stock_status->name;
        } elseif ($this->price === 0) {
            $status = StockStatus::whereSlug(StockStatus::SLUG_WAITING)->value('name');
        } else {
            $status = StockStatus::whereSlug(StockStatus::SLUG_IN_STOCK)->value('name');
        }
        return $status;
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\MorphOne
     */
    public function thumb()
    {
        return $this->morphOne(Images::class, 'imageable');
    }

    public function seo()
    {

        return $this->morphOne(Seo::class, 'seoable');
    }

    public function attributes()
    {
        return $this->morphMany(Attribute::class, 'attributable');
    }

    public function attribute()
    {
        return $this->morphOne(Attribute::class, 'attributable');
    }

    public function categories()
    {

        return $this->belongsToMany(Category::class);
    }

    public function categoryById($id)
    {

        return Category::find($id);
    }

    public function manufacturer()
    {

        return $this->hasOne(Manufacturer::class, 'id', 'manufacturer_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function stockStatus()
    {
        return $this->hasOne(StockStatus::class, 'id', 'stock_status_id');
    }

    public function setSpecialAttribute($value)
    {
        return $this->attributes['special'] = isset($value) ? 1 : 0;
    }
}

application/app/Http/Controllers/Front/ProductsController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class ProductsController extends Controller
{
	protected $client_id = 0;

	public function __construct()
	{
		$this->middleware(function($request, $next){
			if(Auth::check()){

				$this->client_id = Auth::user()->id;
			}
			return $next($request);
		});
	}

	public function show($id)
	{
	    /** @var Product $product */
    	$product = Product::where('id', $id)->with('seo','attributes')->firstOrFail();

    	return view('front.pages.products.show',[
    		'product' => $product,
		    'client_id' => $this->client_id,
	    ]);
    }
}

application/resources/views/admin/pages/products/index.blade.php
@extends('admin.layouts.app')
@section('title')
    {{ trans('interface.panel.products_list.title') }}
@stop
@section('styles')
    <link rel="stylesheet" href="{{ asset('ace/components/chosen/chosen.css') }}">
    @parent
@stop
@section('content')
    @include("admin.layouts._main.header")
    <div class="container main-container">
        @include('admin.layouts._sidebar.sidebar', ['active' => 'products_list'])
        <div class="content">
            <div class="page-content">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="page-header">
                            <div class="row">
                                <div class="col-sm-6 col-xs-12 text-left">
                                    <h1>
                                        {{ trans('interface.panel.products_list.title') }}
                                    </h1>
                                </div>
                            </div>
                        </div>
                        @if (session('success'))
                            <div class="alert alert-success">{{ session()->get('success') }}</div>
                        @endif
                        @if (session('danger'))
                            <div class="alert alert-danger">{{ session()->get('danger') }}</div>
                        @endif

                        <div class="row">
                            <div class="col-xs-12 text-right">
                                <div class="pull-right tableTools-container">
                                    <button class="btn btn-xs btn-danger tooltip-info" data-rel="tooltip"
                                            data-placement="top" data-original-title="Удалить выбранные"
                                            onclick="deleteProducts(false);">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                @include("admin.pages.products._parts._filter", ['categories' => $categories])
                            </div>
                        </div>
                        <table class="table table-striped table-bordered table-hover">
                            <thead class="thin-border-bottom">
                            <tr>
                                <th class="center sorting_disabled">
                                    <label class="pos-rel">
                                        <input type="checkbox" class="ace">
                                        <span class="lbl"></span>
                                    </label>
                                </th>
                                <th>
                                    id 1c
                                </th>
                                <th>
                                    Название
                                </th>
                                <th>
                                    Категория
                                </th>
                                <th>
                                    Модель
                                </th>
                                <th>
                                    Цена
                                </th>
                                <th class="text-center">
                                    <i class="ace-icon fa fa-cogs"></i>
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($products as $product)
                                <tr>
                                    <td class="center sorting_disabled">
                                        <label class="pos-rel">
                                            <input type="checkbox" class="ace">
                                            <span class="lbl"></span>
                                        </label>
                                    </td>
                                    <td>{{$product->id_1c}}</td>
                                    <td>{{$product->name}}</td>
                                    <td>{{$product->categories->first() ? $product->categories->first()->name : ''}}</td>
                                    <td>{{$product->model_product}}</td>
                                    <td>{{$product->price}}</td>
                                    <td>
                                        <a href="{{ route('products.edit', ['id' => $product->id]) }}" class="btn btn-primary btn-xs">
                                            <i class="fa fa-pencil"></i>
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        @if(!isset($products->links))
                            {{ $products->links() }}
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
    @include("admin.layouts._main.footer")
@endsection
@section('scripts')
    @parent
    <script src="{{asset('ace/components/chosen/chosen.jquery.js')}}"></script>
    <script src="{{asset('ace/components/bootbox.js/bootbox.js')}}"></script>
    <script src="{{asset('ace/components/datatables/media/js/jquery.dataTables.js')}}"></script>
    <script src="{{asset('ace/components/_mod/datatables/jquery.dataTables.bootstrap.js')}}"></script>
    <script src="{{asset('ace/components/datatables.net-select/js/dataTables.select.js')}}"></script>
    <script src="{{asset('js/admin/products.js')}}"></script>
@endsection

application/resources/views/admin/pages/products/trash.blade.php
@extends('admin.layouts.app')
@section('title')
    {{ trans('interface.panel.products_trash.title') }}
@stop
@section('styles')
    @parent
@stop
@section('content')
    @include("admin.layouts._main.header")
    <div class="container main-container">
        @include('admin.layouts._sidebar.sidebar', ['active' => 'products_trash'])
        <div class="content">
            <div class="page-content">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="page-header">
                            <div class="row">
                                <div class="col-sm-6 col-xs-12 text-left">
                                    <h1>
                                        {{ trans('interface.panel.products_trash.title') }} <i class="fa fa-trash"></i>
                                    </h1>
                                </div>

                            </div>
                        </div>
                        @if (session('success'))
                            <div class="alert alert-success">{{ session()->get('success') }}</div>
                        @endif
                        @if (session('danger'))
                            <div class="alert alert-danger">{{ session()->get('danger') }}</div>
                        @endif

                        <div class="row">
                            <div class="col-xs-12 text-right">
                                <div class="pull-right tableTools-container">
                                    <button class="btn btn-xs btn-success tooltip-info" data-rel="tooltip" data-placement="top" data-original-title="Восстановить выбранные" onclick="restoreProducts()">
                                        <i class="fa fa-mail-reply-all"></i>
                                    </button>
                                    <button class="btn btn-xs btn-danger tooltip-info" data-rel="tooltip" data-placement="top" data-original-title="Удалить выбранные" onclick="deleteProducts(true)">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                        <table id="productsTrashTable" class="table table-striped table-bordered table-hover">
                            <thead class="thin-border-bottom">
                            <tr>
                                <th class="center sorting_disabled">
                                    <label class="pos-rel">
                                        <input type="checkbox" class="ace">
                                        <span class="lbl"></span>
                                    </label>
                                </th>
                                <th>
                                    id
                                </th>
                                <th>
                                    Название
                                </th>
                                <th>
                                    Категория
                                </th>
                                <th>
                                    Модель
                                </th>
                                <th>
                                    Цена
                                </th>
                                <th>
                                    Статус
                                </th>
                            </tr>
                            </thead>
                            <tbody></tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
    @include("admin.layouts._main.footer")
@endsection
@section('scripts')
    @parent
    <script src="{{asset('ace/components/bootbox.js/bootbox.js')}}"></script>
    <script src="{{asset('ace/components/datatables/media/js/jquery.dataTables.js')}}"></script>
    <script src="{{asset('ace/components/_mod/datatables/jquery.dataTables.bootstrap.js')}}"></script>
    <script src="{{asset('ace/components/datatables.net-select/js/dataTables.select.js')}}"></script>
    <script src="{{asset('js/admin/products.js')}}"></script>
@endsection